act_list = ["listening songs",
 "talk with a friend on phone",
 "chat with a friend on phone",
 "try a new recipe",
 "read a book amagazine or a newspaper",
 "doing paper crafts",
 "play a game on your phone or computer",
 "doing crossword puzzles",
 "use social media about 1hr",
 "arrange the furniture in your house",
 "write a short poem",
 "arrange a candlelight dinner at home",
 "do simple exercises at home",
 "play an instrument",
 "go for a walk",
 "go for a drive or ride",
 "visit beach, river or lake",
 "go to a local museum or library",
 "clean the garden",
 "go shopping alone",
 "go shopping with friends",
 "go to the friend's home",
 "go to the theater with friend",
 "going out for a dinner with family",
 "play badminton",
 "fly a kite in the park",
 "planting flowerpalnts in the garden",
 "go for a hike",
 "playing golf",
 "go camping",
 "watering flowers in the garden",
 "watch tv with family members",
 "go to the temple or church",
 "watch tv alone",
 "building a rubik's cube",
 "get breakfast with family",
 "do a painting in a paper",
 "get breakfast alone",
 "go to the saloon",
 "play with pet at park"]